Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u1472278/QAnon/QAnon_chpc/parler_week.py", line 4, in <module>
    df = pd.read_csv("../largedata/new_range/parler_huge.csv").head(1000000)
  File "/uufs/chpc.utah.edu/common/home/u1472278/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/uufs/chpc.utah.edu/common/home/u1472278/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/uufs/chpc.utah.edu/common/home/u1472278/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/uufs/chpc.utah.edu/common/home/u1472278/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/uufs/chpc.utah.edu/common/home/u1472278/.local/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../largedata/new_range/parler_huge.csv'
